// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Third_Tier.Data;

namespace Third_Tier.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Third_Tier.Data.Entities.User", b =>
                {
                    b.Property<string>("email")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("password");

                    b.Property<int>("score");

                    b.Property<int>("stage");

                    b.Property<string>("username");

                    b.HasKey("email");

                    b.ToTable("Users");

                    b.HasData(
                        new { email = "a@gmail.com", password = "password1", score = 5, stage = 0, username = "John" },
                        new { email = "b@gmail.com", password = "password2", score = 87, stage = 5, username = "Max" },
                        new { email = "c@gmail.com", password = "password3", score = 23, stage = 5, username = "Daniela" },
                        new { email = "d@gmail.com", password = "password4", score = 50, stage = 6, username = "Lukas" },
                        new { email = "e@gmail.com", password = "password5", score = 50, stage = 7, username = "Alex" },
                        new { email = "f@gmail.com", password = "password6", score = 46, stage = 4, username = "Ilie" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
